// <auto-generated />
namespace GeneralStoreMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedQuantityforTransactins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedQuantityforTransactins));
        
        string IMigrationMetadata.Id
        {
            get { return "201904302043595_Added Quantity for Transactins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
